# Configuration for the labeler GitHub Action

documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

tests:
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*', '**/*test*.py']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['requirements.txt', 'pyproject.toml', 'setup.py']

ui:
  - changed-files:
    - any-glob-to-any-file: ['rpi_usb_cloner/ui/**/*']

storage:
  - changed-files:
    - any-glob-to-any-file: ['rpi_usb_cloner/storage/**/*']

hardware:
  - changed-files:
    - any-glob-to-any-file: ['rpi_usb_cloner/hardware/**/*']

services:
  - changed-files:
    - any-glob-to-any-file: ['rpi_usb_cloner/services/**/*']

github-actions:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']
